/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appPreviewIndexRouteImport } from './routes/(app)/preview/index'
import { Route as appInputIndexRouteImport } from './routes/(app)/input/index'
import { Route as appCompleteIndexRouteImport } from './routes/(app)/complete/index'

const appIndexRoute = appIndexRouteImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appPreviewIndexRoute = appPreviewIndexRouteImport.update({
  id: '/(app)/preview/',
  path: '/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const appInputIndexRoute = appInputIndexRouteImport.update({
  id: '/(app)/input/',
  path: '/input/',
  getParentRoute: () => rootRouteImport,
} as any)
const appCompleteIndexRoute = appCompleteIndexRouteImport.update({
  id: '/(app)/complete/',
  path: '/complete/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/complete': typeof appCompleteIndexRoute
  '/input': typeof appInputIndexRoute
  '/preview': typeof appPreviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRoute
  '/complete': typeof appCompleteIndexRoute
  '/input': typeof appInputIndexRoute
  '/preview': typeof appPreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/': typeof appIndexRoute
  '/(app)/complete/': typeof appCompleteIndexRoute
  '/(app)/input/': typeof appInputIndexRoute
  '/(app)/preview/': typeof appPreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/complete' | '/input' | '/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/complete' | '/input' | '/preview'
  id:
    | '__root__'
    | '/(app)/'
    | '/(app)/complete/'
    | '/(app)/input/'
    | '/(app)/preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appCompleteIndexRoute: typeof appCompleteIndexRoute
  appInputIndexRoute: typeof appInputIndexRoute
  appPreviewIndexRoute: typeof appPreviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/preview/': {
      id: '/(app)/preview/'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof appPreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/input/': {
      id: '/(app)/input/'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof appInputIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/complete/': {
      id: '/(app)/complete/'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof appCompleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appIndexRoute: appIndexRoute,
  appCompleteIndexRoute: appCompleteIndexRoute,
  appInputIndexRoute: appInputIndexRoute,
  appPreviewIndexRoute: appPreviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
